language: node_js
node_js:
  - "0.10"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install --quiet -g "gulpjs/gulp-cli#4.0" karma bower
  - npm install
  - bower install

script: gulp build

deploy:
  provider: s3
  access_key_id: "AKIAIXIVXTFWJLTK2LPA"
  secret_access_key: "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"
  bucket: "451ordercloudtest"
  skip_cleanup: true
  region: Oregon
  endpoint: s3-website-us-west-2.amazonaws.com
  local_dir: build